import Button from "./Button";

const FilterButtons = () => {
  const filters = [
    "All",
    "Mixes",
    "Music",
    "Crickets",
    "Technology",
    "Computer Science",
    "GeoPolitics",
    "War",
    "Podcasts",
    "Javascript",
    "Tourism",
    "Comedy",
    "Gaming",
    "Movies",
    "TV Shows",
    "Sports",
    "Fitness",
    "Food",
    "Travel",
    "News",
    "Fashion",
    "Beauty",
    "DIY",
    "Education",
    "Science",
    "Art",
    "Animals",
    "Documentaries",
    "Health",
    "Business",
    "Finance",
    "Motivation",
    "History",
    "Politics",
    "Environment",
    "Cars",
    "Pets",
    "Lifestyle",
    "Cooking",
    "Tech Reviews",
    "Tutorials",
    "Vlogs",
    "Live Streams",
    "Short Films",
    "Gardening",
    "Photography",
    "Nature",
    "Fashion",
    "Beauty",
    "DIY",
    "Education",
    "Science",
    "Art",
    "Animals",
    "Documentaries",
    "Health",
    "Business",
    "Finance",
    "Motivation",
    "History",
    "Politics",
    "Environment",
    "Cars",
    "Pets",
    "Lifestyle",
    "Cooking",
    "Tech Reviews",
    "Tutorials",
    "Vlogs",
    "Live Streams",
    "Short Films",
    "Gardening",
    "Photography",
    "Nature",
  ];
  return (
    <div className="fixed z-10 bg-white md:w-[1802px] max-w-full py-2 pb-3   px-4 flex items-center gap-2 rounded overflow-hidden overflow-x-scroll no-scrollbar  select-none">
      {filters.map((filter, index) => (
        <Button title={filter} key={index} />
      ))}
    </div>
  );
};

export default FilterButtons;
